services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-firebase-app
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html/laravel/gestion-ecole
    volumes:
      - ./:/var/www/html/laravel/gestion-ecole
    networks:
      - app-network
    command: ["/var/www/html/laravel/gestion-ecole/start.sh"]

  webserver:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html/laravel/gestion-ecole
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge