version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - .:/var/www
      - ./storage/firebase/gestion-ecole-dbb48-firebase-adminsdk-8kf73-483e779f07:/var/www/html/laravel/gestion-ecole/storage/firebase/gestion-ecole-dbb48-firebase-adminsdk-8kf73-483e779f07.json
    networks:
      - laravel
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: gestion_ecole
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      APP_PORT: 8080  
      FIREBASE_CREDENTIALS: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiZ2VzdGlvbi1lY29sZS1kYmI0OCIsCiAgInByaXZhdGVfa2V5X2lkIjogIjJiYTJlMWNjNzI1NDY4Zjk4Y2Y3ZTU5YTNjN2Q3MWQ0OWYwZGQ4ZmIiLAogICJwcml2YXRlX2tleSI6ICItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cbk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRRElrdk1PeWdreVByQzVcbm9iUlA1WVVRMFBBaU80RHZqYTZWS3IzY1RQYmRxalFUQkJHQk5aQjBsWCt2RU1ib1Vpc2dEUmFZQWJaamNvWHNcbm5nN21JTFJLbXIzYXJDTlNnTFEyY0R3QVIraG4rRVBJMkQ1TVBjTE1DNEF0ckdVVjg3VHNyWHYyZ2JERHNXK3Zcbko0VVh6MEdqbkY4aEJ0T0JEWEhnQ3A2WDhHNXFEV08vYlQveXFlaVF3UkpzdnhIQVJGeFNIRWRheE1saU8wY3pcblZRZGt5ZGMwc1FyNW52aFhWZ25QTitDUTEwWW5KT3FseCtzRU1KdVlieXNVMEVzd216dXFQalBmVGlYV0lQdnJcbjR4a0xNbDJDZDN0RW4rMlZjSVdtbVlXWUVPSkdMK2RVZGtCWEh6VzlmVlZXT2ZBZUN3cjFsY3ZGZjZYZnZQekNcbnU5TnJRK3QvQWdNQkFBRUNnZ0VBVFpiSy80V1lXUjkzTGRnbjhHQlJRVmdTREt3SURLTTZUZW5pMkQzTm9hSWRcbjB0MVlDQ3U0WGVFWEs1bkoyRVV3K1kwV21HYlJMMWMyQjNwOU9QaWR4ZDVtWXhrRDhQNW91RVppYjVsaGhoYTdcbjRnNEV5Mmw0MllYNVo3R3d5UFVsb0FqY1UxZUlFYXVxRUkreEpLekFMNUptR2xpUnFQS1NncUNaQ1IyeEdNUzFcbjJEU25HTSt4QS81QnJiWjM1Tmd2K0krOExJaU8wTk1lZ2R0Y0JwclYyZ2N2WUh4ajRZK0RuVklzalh5blE0cG9cbitUaVRJNXdoa2xhT2pBM1dOTXBYN2Fkc2kzOVRBeENpdEpPTG9Fb200TEhyMWVnc3RNMG9SdzU1L2xpSUZaL01cbmZxaDdRTlhaZE1sdnpCdldCYzE4TUphaUIyaW1ybU0rM3VzeWJ0eVp3UUtCZ1FEbzFWMElNazRETmdSdGNRRk9cbjlySzVvcnhvWG1KcmRKYUE4WlRLNGk2eHhISHpyWmZrN1hHRFF0OEhEcnNpR3lYNEdpWGxJeUV0WDg5SHhYK25cblNvTEJtbkFtTFljUm4wQmpXTHJacU42VVZvU3lsSTFoalBCa0YvaTZwNlRONHVyM3ZLbmt6TnpWSThCQ2drRW9cbkpSY3hoeW9SQ0Z4UEt5WEt3bU5tbFQ0ZVRRS0JnUURjaCtNbDdJOHNwZlBzV3ViU2xsb1cxOFROSzZ6UWkza29cbm1Zcnc5V2phdndvVlhJek94T1orTGNYakgvSm90Y2l5WGc1TzhmT0NHL0lJN1pyR205blNtWGNIU0hxWHlQbm5cblNRUTNiYjExTmJjS05FWGwrWWx6V091V09GKzhXbmNVbTJJYjgyMVVuanV4d0l3Ylo0SXJDb3VJQnZJOS91UWdcbnhkYURXb1FPK3dLQmdCalA1QUlqbWp5dFhQdHN0Mzc2dTBFZEhvYmd5QXc3ZUc1MVVDM3V2SnNsSEIranVEUWxcbk9adUxYTWtid01WNXJ5b3BYekJ6OWUwbjhLYnRYUlV1MDVCZUxPVmtwS2cwR0dCOTdDdVYyMkpqZGZDeDgvOFpcblRlVGN5UnpiRUswQUtab00rTzN4QnZlUHY4VldyQ3JqQ1AyMk1iMXU3cWRoS2IzWnlVMzlTWWxoQW9HQU5BYW1cbjB0cVZDRjU2UmlkSHp5U0RTbUpLM25CUVM3NnJyYVZUZnZjV2JveWxMMWJ2TFJTTW4vWGllbXVkLzQvck1oRTRcblpPMTFtaHRIcFUyUXR3d3JmaUNRVVJxTE9XWERkd25sd2NIVThXTGp0TGVTU2VmdHdsV1c5cENFSFdabU0ybFlcbjR1a3h3TVczcFg2Y1R4YkRRYTR5THJ3Y3gvMXJDa1JDRUNqNWdLTUNnWUVBMFJLbVBFdGR0aUJ1QU9zYXludjFcbmVzTDJuSk9hdjV2SE5JNkdENTRiU2lpaU9BZ3ByVlhIODJNVjBERnA3N3FYMDhzeWRBNDFZQlJXNjhCSjRLd1BcbnNRTWtWa3NROFJxQndZMHBZRkF4YWc4MXVtRE1jNm1jL0RCNWxEUHBmbWRiKzRralZQT0d6aFJ0OVlNb09hdThcbk10VDNKY0hjcjBpR0t1QTdDV09Pb2RnPVxuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxuIiwKICAiY2xpZW50X2VtYWlsIjogImZpcmViYXNlLWFkbWluc2RrLThrZjczQGdlc3Rpb24tZWNvbGUtZGJiNDguaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTAwMTk5Mzg3OTUxNjI1NTk2NzQxIiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9maXJlYmFzZS1hZG1pbnNkay04a2Y3MyU0MGdlc3Rpb24tZWNvbGUtZGJiNDguaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJ1bml2ZXJzZV9kb21haW4iOiAiZ29vZ2xlYXBpcy5jb20iCn0=

      GOOGLE_APPLICATION_CREDENTIALS: /var/www/firebase-key.json
    expose:
      - 8080  # Assurez-vous que votre application écoute sur ce port

  webserver:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"  # Assurez-vous que PORT est défini
    depends_on:
      - app
    networks:
      - laravel

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: gestion_ecole
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  postgres_data: